[build]
  publish = "."
  command = "node inject-env.js"

[build.environment]
  # These environment variables will be set in Netlify dashboard
  # OPENROUTER_API_KEY = "your-api-key-here"
  # SITE_URL = "https://your-site.netlify.app"
  # SITE_NAME = "PnCoder"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  # Production environment variables
  # Set these in Netlify dashboard under Site settings > Environment variables

[context.deploy-preview]
  # Deploy preview environment variables
  # These can be different from production for testing

[context.branch-deploy]
  # Branch deploy environment variables
  # These can be different from production for testing